# vlabs/docker-compose.yml
version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app/backend
      - /var/run/docker.sock:/var/run/docker.sock
      - ./public:/public
      - ./python_pipeline:/python_pipeline # This mount is correct for the backend to see scripts.yaml
    environment:
      # --- IMPORTANT: REPLACE THIS WITH YOUR ACTUAL HOST PATH ---
      HOST_PROJECT_ROOT: "/home/nikos/github/ngeran/vlabs" # <--- YOUR ACTUAL PATH HERE! (NO trailing slash)
    restart: unless-stopped
    command: node server.js

  python_runner:
    build:
      context: ./python_pipeline
      dockerfile: Dockerfile_python_runner
    volumes:
      # This mount is correct for the python_runner image build,
      # but the runtime mount will come from server.js's docker run command.
      - ./python_pipeline:/app/python-scripts
    # ... (rest of python_runner service)
