version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: '%(asctime)s - %(levelname)s - %(name)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: WARNING
    formatter: simple
    stream: ext://sys.stdout
  jsnapy_file:
    class: logging.FileHandler
    level: INFO
    formatter: simple
    filename: /tmp/jsnapy/jsnapy.log

root:
  level: WARNING
  handlers: [console]

loggers:
  # Write JSNAPy details to file only, not console
  jsnapy:
    level: INFO
    handlers: [jsnapy_file]
    propagate: false

  # Keep these noisy libs at WARNING everywhere
  ncclient:
    level: WARNING
    propagate: true
  ncclient.transport:
    level: WARNING
    propagate: true
  ncclient.transport.parser:
    level: WARNING
    propagate: true
  paramiko:
    level: WARNING
    propagate: true