# test_config.yml - Dynamic test configuration
tests:
  test_version:
    file: 'test_version.yml'
    description: 'Check Junos version information'
    rpc_fallback: 'get_software_information'
    enabled: true
    timeout: 30
    xpath_checks:
      - path: ".//junos-version"
        expected_min_length: 1
    
  test_bgp:
    file: 'test_bgp.yml'
    description: 'Check BGP neighbor status'
    rpc_fallback: 'get_bgp_neighbor_information'
    enabled: true
    timeout: 60
    thresholds:
      min_neighbors: 1
      max_down_neighbors: 0
    xpath_checks:
      - path: ".//bgp-peer"
        attribute: "peer-state"
        expected_values: ["Established"]
    
  test_interfaces:
    file: 'test_interfaces.yml'
    description: 'Check interface status and statistics'
    rpc_fallback: 'get_interface_information'
    enabled: true
    timeout: 45
    parameters:
      terse: true
      interface_type: "physical"
    thresholds:
      min_up_interfaces: 1
    
  test_ospf:
    file: 'test_ospf.yml'
    description: 'Check OSPF neighbor and database information'
    rpc_fallback: 'get_ospf_neighbor_information'
    enabled: true
    timeout: 40
    thresholds:
      min_neighbors: 0
    
  test_route_table:
    file: 'test_route_table.yml'
    description: 'Check routing table entries'
    rpc_fallback: 'get_route_information'
    enabled: true
    timeout: 60
    parameters:
      table: 'inet.0'
    thresholds:
      min_routes: 1
      max_routes: 1000000
    
  test_system_health:
    file: 'test_system_health.yml'
    description: 'Check system alarms and hardware status'
    rpc_fallback: 'get_system_alarm_information'
    enabled: true
    timeout: 30
    thresholds:
      max_alarms: 0
    critical: true
    
  test_lldp:
    file: 'test_lldp.yml'
    description: 'Check LLDP neighbor information'
    rpc_fallback: 'get_lldp_neighbors_information'
    enabled: true
    timeout: 30
    
  test_mpls:
    file: 'test_mpls.yml'
    description: 'Check MPLS LSP status'
    rpc_fallback: 'get_mpls_lsp_information'
    enabled: true
    timeout: 45

# Global settings
global:
  default_timeout: 30
  max_concurrent_tests: 5
  retry_attempts: 2
  retry_delay: 5
  log_level: "INFO"
  output_format: "json"  # json, yaml, table
  
# Device-specific overrides (optional)
device_profiles:
  router:
    tests:
      test_bgp:
        thresholds:
          min_neighbors: 2
      test_ospf:
        thresholds:
          min_neighbors: 1
  
  switch:
    tests:
      test_lldp:
        thresholds:
          min_neighbors: 2
      test_interfaces:
        thresholds:
          min_up_interfaces: 10
